require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MonitsController do

  # This should return the minimal set of attributes required to create a valid
  # Monit. As you add validations to Monit, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MonitsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all monits as @monits" do
      monit = Monit.create! valid_attributes
      get :index, {}, valid_session
      assigns(:monits).should eq([monit])
    end
  end

  describe "GET show" do
    it "assigns the requested monit as @monit" do
      monit = Monit.create! valid_attributes
      get :show, {:id => monit.to_param}, valid_session
      assigns(:monit).should eq(monit)
    end
  end

  describe "GET new" do
    it "assigns a new monit as @monit" do
      get :new, {}, valid_session
      assigns(:monit).should be_a_new(Monit)
    end
  end

  describe "GET edit" do
    it "assigns the requested monit as @monit" do
      monit = Monit.create! valid_attributes
      get :edit, {:id => monit.to_param}, valid_session
      assigns(:monit).should eq(monit)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Monit" do
        expect {
          post :create, {:monit => valid_attributes}, valid_session
        }.to change(Monit, :count).by(1)
      end

      it "assigns a newly created monit as @monit" do
        post :create, {:monit => valid_attributes}, valid_session
        assigns(:monit).should be_a(Monit)
        assigns(:monit).should be_persisted
      end

      it "redirects to the created monit" do
        post :create, {:monit => valid_attributes}, valid_session
        response.should redirect_to(Monit.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved monit as @monit" do
        # Trigger the behavior that occurs when invalid params are submitted
        Monit.any_instance.stub(:save).and_return(false)
        post :create, {:monit => { "name" => "invalid value" }}, valid_session
        assigns(:monit).should be_a_new(Monit)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Monit.any_instance.stub(:save).and_return(false)
        post :create, {:monit => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested monit" do
        monit = Monit.create! valid_attributes
        # Assuming there are no other monits in the database, this
        # specifies that the Monit created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Monit.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => monit.to_param, :monit => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested monit as @monit" do
        monit = Monit.create! valid_attributes
        put :update, {:id => monit.to_param, :monit => valid_attributes}, valid_session
        assigns(:monit).should eq(monit)
      end

      it "redirects to the monit" do
        monit = Monit.create! valid_attributes
        put :update, {:id => monit.to_param, :monit => valid_attributes}, valid_session
        response.should redirect_to(monit)
      end
    end

    describe "with invalid params" do
      it "assigns the monit as @monit" do
        monit = Monit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Monit.any_instance.stub(:save).and_return(false)
        put :update, {:id => monit.to_param, :monit => { "name" => "invalid value" }}, valid_session
        assigns(:monit).should eq(monit)
      end

      it "re-renders the 'edit' template" do
        monit = Monit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Monit.any_instance.stub(:save).and_return(false)
        put :update, {:id => monit.to_param, :monit => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested monit" do
      monit = Monit.create! valid_attributes
      expect {
        delete :destroy, {:id => monit.to_param}, valid_session
      }.to change(Monit, :count).by(-1)
    end

    it "redirects to the monits list" do
      monit = Monit.create! valid_attributes
      delete :destroy, {:id => monit.to_param}, valid_session
      response.should redirect_to(monits_url)
    end
  end

end
